### ISSUE TITLE
Nothing showing up :)

### ISSUE THREAD

**Issue by goxr3plus** [git-insights/git-insights#14]
I am a new user on it connected one of my repositories , XR3Player and i don't see nothing showing up :) 

![image](https://user-images.githubusercontent.com/20374208/79116507-5780a500-7d91-11ea-86dd-8fcc0f3e48f2.png)

![chrome_2020-04-13_14-15-34](https://user-images.githubusercontent.com/20374208/79116510-5b142c00-7d91-11ea-9721-8e9007e41448.png)

I want my money back . I am joking :)

Good luck with this project .

Why it doesn't showing anything by the way :?

**Comment by muratsu** [comment]
Hey sorry about the late reply! By default, we show the activity from the last two weeks. Did you have any activity in the last two weeks?

**Comment by goxr3plus** [comment]
Just some commits :), i will try for another project

**Comment by muratsu** [comment]
Hey @goxr3plus, do you have any data? I've checked your repository XR3Player, and there should be some data available on the dashboard.

**Comment by goxr3plus** [comment]
Yes now i can see data :)
